package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseDialogRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DialogRecord extends BaseDialogRecord<DialogRecord> {
	public static final DialogRecord dao = new DialogRecord().dao();
}
