package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseDialog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dialog extends BaseDialog<Dialog> {
	public static final Dialog dao = new Dialog().dao();
}
