package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseHdOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HdOrder extends BaseHdOrder<HdOrder> {
	public static final HdOrder dao = new HdOrder().dao();
}
