package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseMsgTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgTemplate extends BaseMsgTemplate<MsgTemplate> {
	public static final MsgTemplate dao = new MsgTemplate().dao();
}
