package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order().dao();
}
