package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Question extends BaseQuestion<Question> {
	public static final Question dao = new Question().dao();
}
