package com.pagoda.hdtt.aotogen;

import com.pagoda.hdtt.aotogen.base.BaseRepositoryContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RepositoryContent extends BaseRepositoryContent<RepositoryContent> {
	public static final RepositoryContent dao = new RepositoryContent().dao();
}
