package com.pagoda.hdtt.common.model;

import com.pagoda.hdtt.common.model.base.BaseMsgTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgTemplate extends BaseMsgTemplate<MsgTemplate> {
	public static final MsgTemplate dao = new MsgTemplate().dao();
}
