package com.pagoda.hdtt.aotogen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRepositoryContent<M extends BaseRepositoryContent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setQuestion(java.lang.String question) {
		set("question", question);
	}
	
	public java.lang.String getQuestion() {
		return getStr("question");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}
	
	public java.lang.String getCreater() {
		return getStr("creater");
	}

	public void setDelete(java.lang.Integer delete) {
		set("delete", delete);
	}
	
	public java.lang.Integer getDelete() {
		return getInt("delete");
	}

}
