package com.pagoda.hdtt.aotogen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHdOrder<M extends BaseHdOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	/**
	 * 商品名称
	 */
	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goodsName");
	}

	/**
	 * 单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 数量
	 */
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	/**
	 * 数量
	 */
	public java.lang.Integer getCount() {
		return getInt("count");
	}

	/**
	 * 数量单位(斤; 个;盒d等等)
	 */
	public void setCountUnit(java.lang.String countUnit) {
		set("countUnit", countUnit);
	}
	
	/**
	 * 数量单位(斤; 个;盒d等等)
	 */
	public java.lang.String getCountUnit() {
		return getStr("countUnit");
	}

	/**
	 * 总金额
	 */
	public void setTotalMoney(java.lang.String totalMoney) {
		set("totalMoney", totalMoney);
	}
	
	/**
	 * 总金额
	 */
	public java.lang.String getTotalMoney() {
		return getStr("totalMoney");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 图片地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 图片地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

}
