package com.pagoda.hdtt.aotogen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDialogRecord<M extends BaseDialogRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	/**
	 * 消息内容
	 */
	public void setMessage(java.lang.String message) {
		set("message", message);
	}
	
	/**
	 * 消息内容
	 */
	public java.lang.String getMessage() {
		return getStr("message");
	}

	/**
	 * 创建类型(tuling:机器人  user:用户)
	 */
	public void setCreateType(java.lang.String createType) {
		set("createType", createType);
	}
	
	/**
	 * 创建类型(tuling:机器人  user:用户)
	 */
	public java.lang.String getCreateType() {
		return getStr("createType");
	}

	/**
	 * 创建人
	 */
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	/**
	 * 关联的问题id列表,逗号分隔
	 */
	public void setRelationQuestionId(java.lang.String relationQuestionId) {
		set("relationQuestionId", relationQuestionId);
	}
	
	/**
	 * 关联的问题id列表,逗号分隔
	 */
	public java.lang.String getRelationQuestionId() {
		return getStr("relationQuestionId");
	}

	/**
	 * 会话id
	 */
	public void setDialogId(java.lang.Integer dialogId) {
		set("dialogId", dialogId);
	}
	
	/**
	 * 会话id
	 */
	public java.lang.Integer getDialogId() {
		return getInt("dialogId");
	}

}
