package com.pagoda.hdtt.aotogen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRepositoryContent<M extends BaseRepositoryContent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 创建时间
	 */
	public void setCraeteDate(java.util.Date craeteDate) {
		set("craeteDate", craeteDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCraeteDate() {
		return get("craeteDate");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	/**
	 * 知识库标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 知识库标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 知识库内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 知识库内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 创建人
	 */
	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreater() {
		return getStr("creater");
	}

	/**
	 * 是否已删除(0:未删除   1:已删除)
	 */
	public void setDelete(java.lang.Integer delete) {
		set("delete", delete);
	}
	
	/**
	 * 是否已删除(0:未删除   1:已删除)
	 */
	public java.lang.Integer getDelete() {
		return getInt("delete");
	}

}
